import type { Repo } from "@/types";

// Placeholder data so the grid renders during Phase 0. Replaced by the real
// scanner (Rust IPC) in Phase 1 — see the "Repo scanner" issue.
const HOUR = 3600;
const DAY = 24 * HOUR;
const now = Math.floor(Date.UTC(2026, 5, 1) / 1000); // fixed for deterministic UI

export const MOCK_REPOS: Repo[] = [
  {
    id: "/home/seb/dev/personal/Orrery",
    displayName: "Orrery",
    slug: "Hankanman/Orrery",
    path: "~/dev/personal/Orrery",
    description: "every repo in orbit — a Linux-native command center for your git repos.",
    language: "Rust",
    git: { branch: "main", ahead: 2, behind: 0, dirty: 7 },
    lastCommitUnix: now - 1 * HOUR,
    activity: "active",
    root: "~/dev/personal",
    host: "github",
    stars: 128,
    favorite: true,
    aiSummary:
      "Active Tauri + React project in early development. Phase 1 (local-first grid) is underway; recent work touches the scanner and card layout.",
  },
  {
    id: "/home/seb/dev/personal/dotfiles",
    displayName: "dotfiles",
    slug: "Hankanman/dotfiles",
    path: "~/dev/personal/dotfiles",
    description: "My Linux environment — zsh, neovim, hyprland, the works.",
    language: "Shell",
    git: { branch: "main", ahead: 0, behind: 0, dirty: 0 },
    lastCommitUnix: now - 5 * DAY,
    activity: "idle",
    root: "~/dev/personal",
    host: "github",
    stars: 34,
    favorite: false,
    aiSummary: null,
  },
  {
    id: "/home/seb/dev/work/api-gateway",
    displayName: "API Gateway",
    slug: "acme/api-gateway",
    path: "~/dev/work/api-gateway",
    description: "Edge gateway: auth, rate limiting, and request routing.",
    language: "Go",
    git: { branch: "feat/jwt-rotation", ahead: 4, behind: 1, dirty: 3 },
    lastCommitUnix: now - 3 * HOUR,
    activity: "active",
    root: "~/dev/work",
    host: "gitlab",
    stars: 0,
    favorite: false,
    aiSummary:
      "Heavy active development on a feature branch — JWT rotation mid-refactor, with uncommitted changes and divergence from main.",
  },
  {
    id: "/home/seb/dev/play/raymarcher",
    displayName: "raymarcher",
    slug: null,
    path: "~/dev/play/raymarcher",
    description: "A toy SDF raymarcher. No remote — local experiment.",
    language: "C++",
    git: { branch: "main", ahead: 0, behind: 0, dirty: 12 },
    lastCommitUnix: now - 40 * DAY,
    activity: "stale",
    root: "~/dev/play",
    host: null,
    stars: 0,
    favorite: false,
    aiSummary: "Dormant local experiment with a dirty tree — no commits in over a month.",
  },
  {
    id: "/home/seb/dev/work/web-dashboard",
    displayName: "Web Dashboard",
    slug: "acme/web-dashboard",
    path: "~/dev/work/web-dashboard",
    description: "Customer-facing analytics dashboard.",
    language: "TypeScript",
    git: { branch: "main", ahead: 0, behind: 3, dirty: 0 },
    lastCommitUnix: now - 8 * HOUR,
    activity: "active",
    root: "~/dev/work",
    host: "gitlab",
    stars: 0,
    favorite: false,
    aiSummary: "Behind upstream by 3 commits — a pull is due before the next build.",
  },
  {
    id: "/home/seb/dev/personal/synth",
    displayName: "synth",
    slug: "Hankanman/synth",
    path: "~/dev/personal/synth",
    description: "Modular software synthesizer with a node-based patch editor.",
    language: "Rust",
    git: { branch: "dev", ahead: 11, behind: 0, dirty: 1 },
    lastCommitUnix: now - 2 * DAY,
    activity: "idle",
    root: "~/dev/personal",
    host: "github",
    stars: 213,
    favorite: true,
    aiSummary:
      "Steady solo project on a dev branch — 11 commits ahead of main, one stray change pending.",
  },
];
